version: '3.7'
services:
  sep-ui-live-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - PORT=3000
